/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crudmysql;

/**
 *
 * @author omar-
 */
public class VentanaEditarPersona extends javax.swing.JFrame {

    
    static Persona persona;
    /**
     * Creates new form VentanaAgregarPersona
     * @param persona
     */
    public VentanaEditarPersona(Persona persona) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        VentanaEditarPersona.persona=persona;
        nombreTexto.setText(persona.getNombre());
        direccionTexto.setText(persona.getDireccion());
        telefonoTexto.setText(persona.getTelefono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        direccionTexto = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        telefonoTexto = new javax.swing.JTextField();
        botonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo.setText("Datos de la Persona");
        Fondo.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        Nombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nombre.setText("Nombre:");
        Fondo.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, -1, -1));

        nombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextoActionPerformed(evt);
            }
        });
        Fondo.add(nombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 81, 231, -1));

        Direccion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Direccion.setText("Direccion");
        Fondo.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        direccionTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTextoActionPerformed(evt);
            }
        });
        Fondo.add(direccionTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 231, -1));

        Telefono.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Telefono.setText("Telefono");
        Fondo.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        telefonoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTextoActionPerformed(evt);
            }
        });
        Fondo.add(telefonoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 231, -1));

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });
        Fondo.add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextoActionPerformed
        
    }//GEN-LAST:event_nombreTextoActionPerformed

    private void direccionTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTextoActionPerformed

    private void telefonoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextoActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
       
        ConexionMysql con = new ConexionMysql();
        
        con.editarPersona(persona.getId(),nombreTexto.getText(),direccionTexto.getText(),telefonoTexto.getText());
        
        this.dispose();
    }//GEN-LAST:event_botonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEditarPersona(persona).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Direccion;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonEditar;
    private javax.swing.JTextField direccionTexto;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JTextField telefonoTexto;
    // End of variables declaration//GEN-END:variables
}
